/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "stm32f4xx_hal.h"
#include "uart.h"
#include "gpio.h"

int main(void)
{
  HAL_Init();
  LED_Init();
  Button_Init();
  PA0_Init();
  USART2_Init();
  
  /* Loop forever */
	while(1)
  {

    HAL_Delay(10);
  }
}

void SysTick_Handler()
{
  HAL_IncTick();
}


void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	//Do something..

	if(GPIO_Pin == GPIO_PIN_13)
  {
	  HAL_GPIO_TogglePin(LED_PORT,LED_PIN);
	  printf("Button 13 pressed ! \n\r");
	}

	if(GPIO_Pin == GPIO_PIN_0)
  {
	  printf("PA0 is connected to 3.3V using jumper wire! \n\r");
	}
}