/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "stm32f4xx_hal.h"
#include "uart.h"
#include "gpio.h"
#include "tim.h"


uint8_t button_state = 0;

int main(void)
{
  HAL_Init();
  /* LED_Init();
  Button_Init(); */
  tim_timebase_init();
  USART2_Init();

  /* Loop forever */
	while(1)
  {
    /* button_state = HAL_GPIO_ReadPin (BTN_PORT, BTN_PIN);
    HAL_GPIO_WritePin(LED_PORT, LED_PIN, button_state);
    printf("Printf is being used ! \r\n");
    HAL_Delay(10); */
  }
}

void HAL_TIM_PeriodElapsedCallback( TIM_HandleTypeDef *htim)
{
	//Do somthing
	printf("A second just elapsed ! \n\r");

}

void SysTick_Handler()
{
  HAL_IncTick();
}
